stages:
  - build
  - test

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
  NUGET_PACKAGES: "$CI_PROJECT_DIR/.nuget/packages"
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"

cache:
  policy: pull-push

backend_build:
  image: mcr.microsoft.com/dotnet/sdk:9.0
  stage: build
  cache:
    key: nuget
    paths:
      - .nuget/packages/
  script:
    - dotnet restore "LaundryAPI.sln"
    - dotnet build "LaundryAPI.sln" -c Release --no-restore

backend_test:
  image: mcr.microsoft.com/dotnet/sdk:9.0
  stage: test
  cache:
    key: nuget
    paths:
      - .nuget/packages/
  needs:
    - backend_build
  script:
    - dotnet test "LaundryAPI.sln" -c Release --no-build

frontend_build:
  image: node:20
  stage: build
  cache:
    key: npm
    paths:
      - .npm/
  script:
    - cd laundry-fontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - laundry-fontend/dist/
    expire_in: 1 week
