apiVersion: v1
kind: Service
metadata:
  name: laundry-api
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: laundry-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
