apiVersion: apps/v1
kind: Deployment
metadata:
  name: laundry-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laundry-api
  template:
    metadata:
      labels:
        app: laundry-api
    spec:
      # Uncomment nếu bạn dùng private registry secret
      # imagePullSecrets:
      #   - name: ghcr-creds
      containers:
        - name: laundry-api
          # TODO: đổi <github-username> thành username/organization GitHub thật
          image: ghcr.io/khoiprovip123/laundry-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:8080"
