apiVersion: apps/v1
kind: Deployment
metadata:
  name: laundry-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laundry-frontend
  template:
    metadata:
      labels:
        app: laundry-frontend
    spec:
      # Uncomment nếu bạn dùng private registry secret
      # imagePullSecrets:
      #   - name: ghcr-creds
      containers:
        - name: laundry-frontend
          # TODO: đổi <github-username> thành username/organization GitHub thật
          image: ghcr.io/khoiprovip123/laundry-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: "Asia/Ho_Chi_Minh"
