apiVersion: v1
kind: Service
metadata:
  name: laundry-frontend
  namespace: laundry
spec:
  type: NodePort
  selector:
    app: laundry-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
